services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV}
    container_name: my_cart_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    command: >
      sh -c "if [ \"$ENV\" = \"prod\" ]; then
               node dist/main.js;
             else
               yarn start:dev;
             fi"

    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: my_cart_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app_network

  test_db:
    image: postgres:latest
    container_name: test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5471:5432"
    # ephemeral volume or named volume
    volumes:
      - test_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_cart_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app_network

volumes:
  pgdata:
  test_pgdata:

networks:
  app_network:
    driver: bridge
